modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/devOS-Sanity-Edition/pastelwonderland/issues"
license = "MIT"

[[mods]]
modId = "pastelwonderland"
version = "${version}"
displayName = "Pastel Wonderland"
authors = "Team Nautical"
description = '''
A Minecraft mod that focuses on surviving in a beautiful, yet chaotic dimension.
'''
#logoFile = ""

[[dependencies.pastelwonderland]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pastelwonderland]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pastelwonderland]]
modId = "architectury"
mandatory = true
versionRange = "[3.2.47,)"
ordering = "AFTER"
side = "BOTH"